/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-23 11:22:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1773971807624L));
    _jspx_dependants.put("jar:file:/C:/Users/ACER/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664432778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"fi\">\r\n");
      out.write("      <div class=\"ft\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"ft-brand\">\r\n");
      out.write("          <a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" aria-label=\"AluGhadi home\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/alughadiweblogo.png\" alt=\"AluGhadi\" class=\"footer-logo-img\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <p>Nepal's premium destination for fine watches. Timeless craftsmanship delivered with care to your doorstep.</p>\r\n");
      out.write("          <div class=\"ft-socials\">\r\n");
      out.write("            <a class=\"ft-social-btn\" href=\"#\" aria-label=\"Facebook\"  title=\"Facebook\">&#128526;</a>\r\n");
      out.write("            <a class=\"ft-social-btn\" href=\"#\" aria-label=\"Instagram\" title=\"Instagram\">&#128247;</a>\r\n");
      out.write("            <a class=\"ft-social-btn\" href=\"#\" aria-label=\"Twitter\"   title=\"Twitter\">&#128038;</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"ft-col\">\r\n");
      out.write("          <h4>Shop</h4>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">All Products</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\">Gifting</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\">For Him</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\">For Her</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"ft-col\">\r\n");
      out.write("          <h4>Company</h4>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/about\">About Us</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\">Contact</a>\r\n");
      out.write("          <a href=\"#\">Careers</a>\r\n");
      out.write("          <a href=\"#\">Blog</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"ft-col\">\r\n");
      out.write("          <h4>Support</h4>\r\n");
      out.write("          <a href=\"mailto:support@alughadi.com\">support@alughadi.com</a>\r\n");
      out.write("          <a href=\"tel:+977XXXXXXXX\">+977-1-XXXX-XXXX</a>\r\n");
      out.write("          <a href=\"#\">Returns &amp; Shipping</a>\r\n");
      out.write("          <a href=\"#\">FAQ</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"fb\">\r\n");
      out.write("        <p>&copy; 2026 AluGhadi Watches &middot; All rights reserved</p>\r\n");
      out.write("        <div style=\"display:flex;gap:0.6rem;align-items:center;flex-wrap:wrap;\">\r\n");
      out.write("          <span class=\"fb-badge\">&#127473;&#127477; Made in Nepal</span>\r\n");
      out.write("          <span class=\"fb-badge\">&#128274; Secure Payments</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>Crafted with precision &amp; passion</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <button id=\"cart-btn\" type=\"button\" onclick=\"openCart()\" aria-label=\"Open cart\">\r\n");
      out.write("    &#128717; Cart (<span id=\"cart-count\">0</span>)\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"modal-ov\" id=\"modal-cart\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Shopping cart\">\r\n");
      out.write("    <div class=\"modal\" style=\"max-width:500px;\">\r\n");
      out.write("      <button class=\"modal-close\" onclick=\"closeModal('cart')\" aria-label=\"Close cart\">&#10005;</button>\r\n");
      out.write("      <div class=\"modal-h\">&#128717; Shopping Cart</div>\r\n");
      out.write("      <div class=\"modal-sub\">Your selected items</div>\r\n");
      out.write("      <div id=\"cart-items\" style=\"max-height:320px;overflow-y:auto;margin:1rem 0;\">\r\n");
      out.write("        <div class=\"cart-empty\">\r\n");
      out.write("          <div class=\"cart-empty-ico\">&#128717;</div>\r\n");
      out.write("          <p>Your cart is empty.<br/>Start exploring our collection!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"border-top:1.5px solid var(--border);padding-top:1rem;margin-top:0.5rem;\">\r\n");
      out.write("        <div style=\"display:flex;justify-content:space-between;font-weight:800;margin-bottom:1rem;font-size:1.05rem;\">\r\n");
      out.write("          <span>Total</span>\r\n");
      out.write("          <span id=\"cart-total\" style=\"color:var(--green);\">NPR 0</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"btn btn-g btn-full\" onclick=\"closeModal('cart')\">\r\n");
      out.write("          Proceed to Checkout &#8594;\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"toast-c\" id=\"toast-container\" aria-live=\"polite\"></div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/app.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    /* ---------- Page Loader ---------- */\r\n");
      out.write("    window.addEventListener('load', function () {\r\n");
      out.write("      var loader = document.getElementById('page-loader');\r\n");
      out.write("      if (loader) {\r\n");
      out.write("        setTimeout(function () { loader.classList.add('loader-done'); }, 200);\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Scrolled nav ---------- */\r\n");
      out.write("    (function () {\r\n");
      out.write("      var nav = document.getElementById('nav');\r\n");
      out.write("      if (!nav) return;\r\n");
      out.write("      window.addEventListener('scroll', function () {\r\n");
      out.write("        nav.classList.toggle('scrolled', window.scrollY > 30);\r\n");
      out.write("      }, { passive: true });\r\n");
      out.write("    })();\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Sidebar ---------- */\r\n");
      out.write("    function toggleSidebar() {\r\n");
      out.write("      document.getElementById('sidebar').classList.toggle('active');\r\n");
      out.write("      document.getElementById('sidebar-overlay').classList.toggle('active');\r\n");
      out.write("      document.body.style.overflow = document.getElementById('sidebar').classList.contains('active') ? 'hidden' : '';\r\n");
      out.write("    }\r\n");
      out.write("    function closeSidebar() {\r\n");
      out.write("      document.getElementById('sidebar').classList.remove('active');\r\n");
      out.write("      document.getElementById('sidebar-overlay').classList.remove('active');\r\n");
      out.write("      document.body.style.overflow = '';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Modals ---------- */\r\n");
      out.write("    function showModal(id) {\r\n");
      out.write("      var m = document.getElementById('modal-' + id);\r\n");
      out.write("      if (m) { m.classList.add('active'); document.body.style.overflow = 'hidden'; }\r\n");
      out.write("    }\r\n");
      out.write("    function closeModal(id) {\r\n");
      out.write("      var m = document.getElementById('modal-' + id);\r\n");
      out.write("      if (m) { m.classList.remove('active'); document.body.style.overflow = ''; }\r\n");
      out.write("    }\r\n");
      out.write("    function openCart() { showModal('cart'); }\r\n");
      out.write("\r\n");
      out.write("    /* Close modal on overlay click */\r\n");
      out.write("    document.querySelectorAll('.modal-ov').forEach(function (ov) {\r\n");
      out.write("      ov.addEventListener('click', function (e) {\r\n");
      out.write("        if (e.target === ov) closeModal(ov.id.replace('modal-', ''));\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Toast Helper ---------- */\r\n");
      out.write("    function showToast(title, msg, icon) {\r\n");
      out.write("      var c = document.getElementById('toast-container');\r\n");
      out.write("      if (!c) return;\r\n");
      out.write("      var t = document.createElement('div');\r\n");
      out.write("      t.className = 'toast';\r\n");
      out.write("      t.innerHTML = '<div class=\"t-ico\">' + (icon || '&#10024;') + '</div>'\r\n");
      out.write("        + '<div><div class=\"t-h\">' + title + '</div>'\r\n");
      out.write("        + (msg ? '<div class=\"t-p\">' + msg + '</div>' : '') + '</div>';\r\n");
      out.write("      c.appendChild(t);\r\n");
      out.write("      setTimeout(function () { t.remove(); }, 4000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Reveal on scroll ---------- */\r\n");
      out.write("    (function () {\r\n");
      out.write("      var els = document.querySelectorAll('.reveal');\r\n");
      out.write("      if (!els.length) return;\r\n");
      out.write("      var io = new IntersectionObserver(function (entries) {\r\n");
      out.write("        entries.forEach(function (e) {\r\n");
      out.write("          if (e.isIntersecting) { e.target.classList.add('vis'); io.unobserve(e.target); }\r\n");
      out.write("        });\r\n");
      out.write("      }, { threshold: 0.12 });\r\n");
      out.write("      els.forEach(function (el) { io.observe(el); });\r\n");
      out.write("    })();\r\n");
      out.write("\r\n");
      out.write("    /* ---------- Smooth anchor scroll ---------- */\r\n");
      out.write("    document.querySelectorAll('a[href^=\"#\"]').forEach(function (a) {\r\n");
      out.write("      a.addEventListener('click', function (e) {\r\n");
      out.write("        var target = document.querySelector(this.getAttribute('href'));\r\n");
      out.write("        if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
