/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-18 10:06:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  request.setAttribute("pageTitle", "About Us | AluGhadi");
  request.setAttribute("pageDesc", "Meet the team behind AluGhadi — Nepal's premium watch destination. Crafted with precision and passion by five passionate developers.");
  request.setAttribute("activeNav", "about");
  request.setAttribute("pageStyle", "about");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"page-hero about-hero\">\r\n");
      out.write("  <div class=\"ph-img\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/about_images/hero_about.png\"\r\n");
      out.write("         alt=\"AluGhadi Workshop\"\r\n");
      out.write("         style=\"object-position: center;\" />\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"ph-ov\"></div>\r\n");
      out.write("  <div class=\"ph-body\">\r\n");
      out.write("    <span class=\"ph-chip\">Our Story</span>\r\n");
      out.write("    <h1 class=\"ph-h\">Crafted with <span>passion</span>,<br>built for <span>precision</span>.</h1>\r\n");
      out.write("    <p class=\"ph-sub\">\r\n");
      out.write("      AluGhadi was born from a shared love of horology and a dream to bring world-class\r\n");
      out.write("      timepieces to Nepal. Five minds, one vision.\r\n");
      out.write("    </p>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"sec\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div class=\"split reveal\">\r\n");
      out.write("      <div class=\"split-body\">\r\n");
      out.write("        <div class=\"sec-tag\">Our Mission</div>\r\n");
      out.write("        <h2 class=\"sec-h\">More than a <em style=\"font-style:normal;color:var(--gold);\">watch</em> store.</h2>\r\n");
      out.write("        <p class=\"sec-sub\" style=\"max-width:480px;\">\r\n");
      out.write("          AluGhadi is Nepal's premier destination for fine timepieces. We believe a watch is\r\n");
      out.write("          more than a device — it's a statement, a companion, and a legacy passed through\r\n");
      out.write("          generations. Our mission is to connect discerning collectors with the world's most\r\n");
      out.write("          celebrated horological craftsmanship, delivered with care to your doorstep.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"about-values\">\r\n");
      out.write("          <div class=\"about-val-chip\">Authentic Brands</div>\r\n");
      out.write("          <div class=\"about-val-chip\">Secured Delivery</div>\r\n");
      out.write("          <div class=\"about-val-chip\">Expert Curation</div>\r\n");
      out.write("          <div class=\"about-val-chip\">After-Sales Care</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"split-stats-grid\">\r\n");
      out.write("        <div class=\"about-stat-card reveal reveal-delay-1\">\r\n");
      out.write("          <div class=\"asc-n\">500<span>+</span></div>\r\n");
      out.write("          <div class=\"asc-l\">Premium Watches</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"about-stat-card reveal reveal-delay-2\">\r\n");
      out.write("          <div class=\"asc-n\">50<span>+</span></div>\r\n");
      out.write("          <div class=\"asc-l\">Global Brands</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"about-stat-card reveal reveal-delay-3\">\r\n");
      out.write("          <div class=\"asc-n\">2K<span>+</span></div>\r\n");
      out.write("          <div class=\"asc-l\">Happy Customers</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"about-stat-card reveal reveal-delay-4\">\r\n");
      out.write("          <div class=\"asc-n\">3<span>yr</span></div>\r\n");
      out.write("          <div class=\"asc-l\">Warranty Support</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"about-marquee-strip\">\r\n");
      out.write("  <div class=\"about-marquee-inner\">\r\n");
      out.write("    <span>Heritage</span><span>Craftsmanship</span>\r\n");
      out.write("    <span>Innovation</span><span>Excellence</span>\r\n");
      out.write("    <span>Nepal</span><span>Precision</span>\r\n");
      out.write("    <span>Heritage</span><span>Craftsmanship</span>\r\n");
      out.write("    <span>Innovation</span><span>Excellence</span>\r\n");
      out.write("    <span>Nepal</span><span>Precision</span>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <span>Heritage</span><span>Craftsmanship</span>\r\n");
      out.write("    <span>Innovation</span><span>Excellence</span>\r\n");
      out.write("    <span>Nepal</span><span>Precision</span>\r\n");
      out.write("    <span>Heritage</span><span>Craftsmanship</span>\r\n");
      out.write("    <span>Innovation</span><span>Excellence</span>\r\n");
      out.write("    <span>Nepal</span><span>Precision</span>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"sec sec-alt\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div style=\"text-align:center;margin-bottom:3.5rem;\" class=\"reveal\">\r\n");
      out.write("      <div class=\"sec-tag\" style=\"justify-content:center;\">Meet the Team</div>\r\n");
      out.write("      <h2 class=\"sec-h\">The <em style=\"font-style:normal;color:var(--gold);\">five</em> behind AluGhadi</h2>\r\n");
      out.write("      <p class=\"sec-sub\" style=\"margin:0.75rem auto 0;text-align:center;\">\r\n");
      out.write("        A group of passionate students who turned a class project into a real e-commerce vision.\r\n");
      out.write("        Different skills, one shared ambition.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"team-grid\">\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"team-card reveal reveal-delay-1\">\r\n");
      out.write("        <div class=\"team-avatar-wrap\">\r\n");
      out.write("          <div class=\"team-avatar\" style=\"background: linear-gradient(135deg, #1a6b38 0%, #3dba62 100%);\">\r\n");
      out.write("            <span>SL</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"team-avatar-ring\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-body\">\r\n");
      out.write("          <div class=\"team-role-chip\">Project Lead</div>\r\n");
      out.write("          <h3 class=\"team-name\">Shisir Lamsal</h3>\r\n");
      out.write("          <p class=\"team-bio\">\r\n");
      out.write("            Visionary project lead who architected the system and kept the team aligned.\r\n");
      out.write("            Passionate about full-stack development and clean code.\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"team-skills\">\r\n");
      out.write("            <span>Java EE</span><span>MVC</span><span>Leadership</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-card-glow\" style=\"background: rgba(26,107,56,0.08);\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"team-card reveal reveal-delay-2\">\r\n");
      out.write("        <div class=\"team-avatar-wrap\">\r\n");
      out.write("          <div class=\"team-avatar\" style=\"background: linear-gradient(135deg, #c9a452 0%, #b8913a 100%);\">\r\n");
      out.write("            <span>DG</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"team-avatar-ring\" style=\"border-color: var(--gold-light);\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-body\">\r\n");
      out.write("          <div class=\"team-role-chip\" style=\"color:var(--gold2);background:var(--gold-light);border-color:rgba(201,164,82,0.25);\">UI / UX</div>\r\n");
      out.write("          <h3 class=\"team-name\">Dikshita GC</h3>\r\n");
      out.write("          <p class=\"team-bio\">\r\n");
      out.write("            The creative force driving AluGhadi's visual identity. Expert at translating\r\n");
      out.write("            ideas into beautiful, accessible interfaces that users love.\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"team-skills\">\r\n");
      out.write("            <span>CSS</span><span>Design Systems</span><span>UX</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-card-glow\" style=\"background: rgba(201,164,82,0.08);\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"team-card reveal reveal-delay-3\">\r\n");
      out.write("        <div class=\"team-avatar-wrap\">\r\n");
      out.write("          <div class=\"team-avatar\" style=\"background: linear-gradient(135deg, #1d4ed8 0%, #3b82f6 100%);\">\r\n");
      out.write("            <span>AT</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"team-avatar-ring\" style=\"border-color: #dbeafe;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-body\">\r\n");
      out.write("          <div class=\"team-role-chip\" style=\"color:#1e40af;background:#eff6ff;border-color:rgba(59,130,246,0.2);\">Backend Dev</div>\r\n");
      out.write("          <h3 class=\"team-name\">Ashish Thapa</h3>\r\n");
      out.write("          <p class=\"team-bio\">\r\n");
      out.write("            Backend architect responsible for database design and servlet infrastructure.\r\n");
      out.write("            Builds robust, scalable systems that power the entire platform.\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"team-skills\">\r\n");
      out.write("            <span>MySQL</span><span>Servlets</span><span>DAO</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-card-glow\" style=\"background: rgba(59,130,246,0.06);\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"team-card reveal reveal-delay-4\">\r\n");
      out.write("        <div class=\"team-avatar-wrap\">\r\n");
      out.write("          <div class=\"team-avatar\" style=\"background: linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%);\">\r\n");
      out.write("            <span>ST</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"team-avatar-ring\" style=\"border-color: #ede9fe;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-body\">\r\n");
      out.write("          <div class=\"team-role-chip\" style=\"color:#6d28d9;background:#f5f3ff;border-color:rgba(124,58,237,0.2);\">Frontend Dev</div>\r\n");
      out.write("          <h3 class=\"team-name\">Sabin Thapa</h3>\r\n");
      out.write("          <p class=\"team-bio\">\r\n");
      out.write("            Frontend specialist who brings designs to life with smooth interactions and\r\n");
      out.write("            pixel-perfect layouts. JavaScript enthusiast with an eye for detail.\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"team-skills\">\r\n");
      out.write("            <span>JavaScript</span><span>JSP</span><span>Animations</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-card-glow\" style=\"background: rgba(124,58,237,0.06);\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <div class=\"team-card reveal reveal-delay-5\">\r\n");
      out.write("        <div class=\"team-avatar-wrap\">\r\n");
      out.write("          <div class=\"team-avatar\" style=\"background: linear-gradient(135deg, #d97706 0%, #f59e0b 100%);\">\r\n");
      out.write("            <span>RP</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"team-avatar-ring\" style=\"border-color: #fde68a;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-body\">\r\n");
      out.write("          <div class=\"team-role-chip\" style=\"color:#b45309;background:#fffbeb;border-color:rgba(217,119,6,0.22);\">QA &amp; Testing</div>\r\n");
      out.write("          <h3 class=\"team-name\">Rijan Pun</h3>\r\n");
      out.write("          <p class=\"team-bio\">\r\n");
      out.write("            Quality guardian who ensures every feature is robust, bug-free, and\r\n");
      out.write("            delivers a flawless experience. Driven by precision and user empathy.\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"team-skills\">\r\n");
      out.write("            <span>Testing</span><span>QA</span><span>Debugging</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"team-card-glow\" style=\"background: rgba(217,119,6,0.06);\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"sec\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div style=\"text-align:center;margin-bottom:3rem;\" class=\"reveal\">\r\n");
      out.write("      <div class=\"sec-tag\" style=\"justify-content:center;\">What We Stand For</div>\r\n");
      out.write("      <h2 class=\"sec-h\">Built on <em style=\"font-style:normal;color:var(--green);\">values</em> that matter</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"feat-grid\">\r\n");
      out.write("      <div class=\"feat-card reveal reveal-delay-1\">\r\n");
      out.write("        <div class=\"feat-card-icon icon-bg-green\">\r\n");
      out.write("          <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><polyline points=\"12 6 12 12 16 14\"/></svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"feat-card-title\">Precision First</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">Every watch we carry is vetted for accuracy, authenticity and craftsmanship. We never compromise on quality.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feat-card reveal reveal-delay-2\">\r\n");
      out.write("        <div class=\"feat-card-icon icon-bg-gold\">\r\n");
      out.write("          <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"8\" r=\"6\"/><path d=\"M12 2v2M12 14v2M6 8H4M20 8h-2M7.05 4.93 5.64 3.51M18.36 3.51l-1.41 1.42M7.05 11.07 5.64 12.49M18.36 12.49l-1.41-1.42\"/></svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"feat-card-title\">Timeless Heritage</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">We celebrate the art of watchmaking by connecting you with heritage brands that have stood the test of time.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feat-card reveal reveal-delay-3\">\r\n");
      out.write("        <div class=\"feat-card-icon icon-bg-blue\">\r\n");
      out.write("          <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/><polyline points=\"9 22 9 12 15 12 15 22\"/></svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"feat-card-title\">Made for Nepal</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">Localised experience, local prices, local support. AluGhadi is proudly rooted in Nepal's growing collector community.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"sec sec-dark\" style=\"padding:4rem 2rem;\">\r\n");
      out.write("  <div class=\"sec-inner\" style=\"text-align:center;\">\r\n");
      out.write("    <div class=\"sec-tag\" style=\"justify-content:center;\">Ready to explore?</div>\r\n");
      out.write("    <h2 class=\"sec-h\" style=\"margin-bottom:1rem;\">Find your <em style=\"font-style:normal;color:var(--accent);\">perfect</em> timepiece</h2>\r\n");
      out.write("    <p class=\"sec-sub\" style=\"margin:0 auto 2rem;text-align:center;\">\r\n");
      out.write("      Browse our curated collection of luxury and everyday watches — something for every wrist.\r\n");
      out.write("    </p>\r\n");
      out.write("    <div style=\"display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn btn-g btn-lg\">Shop Collection</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\"  class=\"btn btn-o btn-lg\" style=\"color:#fff;border-color:rgba(255,255,255,0.25);\">Get in Touch</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
