/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-01 11:05:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1773971807624L));
    _jspx_dependants.put("jar:file:/C:/Users/ACER/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664432778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write(' ');
 request.setAttribute("pageTitle",
"AluGhadi Watches - Premium Watch Collection"); request.setAttribute("pageDesc",
"Discover premium watches with timeless design and exceptional quality.");
request.setAttribute("activeNav", "home"); 
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- HERO -->\r\n");
      out.write("<section class=\"home-hero\">\r\n");
      out.write("  <div class=\"hero-image\">\r\n");
      out.write("    <img\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/hero_home.png\"\r\n");
      out.write("      alt=\"AluGhadi Premium Watches\"\r\n");
      out.write("      style=\"object-position: center top;\"\r\n");
      out.write("    />\r\n");
      out.write("    <div class=\"hero-fade\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"hero-content\">\r\n");
      out.write("    <div class=\"hero-chip\">&#8986; Timeless Elegance</div>\r\n");
      out.write("    <h1 class=\"hero-h\">Discover Premium<br /><span>Watch Collections</span></h1>\r\n");
      out.write("    <p class=\"hero-p\">\r\n");
      out.write("      Handpicked watch collections featuring timeless designs, exceptional\r\n");
      out.write("      craftsmanship, and unmatched quality. From classic to contemporary, find\r\n");
      out.write("      the perfect timepiece for every occasion.\r\n");
      out.write("    </p>\r\n");
      out.write("    <div class=\"hero-btns\">\r\n");
      out.write("      <a class=\"hbtn hbtn-f\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("        >Shop Now</a\r\n");
      out.write("      >\r\n");
      out.write("      <a class=\"hbtn hbtn-o\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        >Explore Gifting &rarr;</a\r\n");
      out.write("      >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero-stats\">\r\n");
      out.write("      <div class=\"hero-stat\">\r\n");
      out.write("        <span class=\"hero-stat-number\">500+</span><span class=\"hero-stat-label\">Watch Models</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"hero-stat\">\r\n");
      out.write("        <span class=\"hero-stat-number\">50+</span\r\n");
      out.write("        ><span class=\"hero-stat-label\">International Brands</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"hero-stat\">\r\n");
      out.write("        <span class=\"hero-stat-number\">99%</span\r\n");
      out.write("        ><span class=\"hero-stat-label\">Customer Satisfaction</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- FEATURED COLLECTIONS -->\r\n");
      out.write("<section class=\"sec\" style=\"background: var(--white)\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div\r\n");
      out.write("      style=\"\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: flex-end;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        gap: 1.5rem;\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("      \"\r\n");
      out.write("    >\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"sec-tag\">Featured Collections</div>\r\n");
      out.write("        <h2 class=\"sec-h\">Curated Watch<br />Collections</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p class=\"sec-sub\">\r\n");
      out.write("        From elegant classics to modern sports watches &mdash; each collection\r\n");
      out.write("        represents the pinnacle of watchmaking.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"dest-scroll\">\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"dest-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        style=\"text-decoration: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"collection-card-image\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Luxury\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collection-card-overlay\"></div>\r\n");
      out.write("        <div class=\"collection-card-chip\">Premium</div>\r\n");
      out.write("        <div class=\"collection-card-body\">\r\n");
      out.write("          <div class=\"collection-card-tag\">High-End Collection</div>\r\n");
      out.write("          <div class=\"collection-card-title\">Luxury Watches</div>\r\n");
      out.write("          <div class=\"collection-card-meta\">Timeless elegance and precision</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"dest-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        style=\"text-decoration: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"collection-card-image\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Sports\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collection-card-overlay\"></div>\r\n");
      out.write("        <div class=\"collection-card-chip\">Active</div>\r\n");
      out.write("        <div class=\"collection-card-body\">\r\n");
      out.write("          <div class=\"collection-card-tag\">Sports &amp; Adventure</div>\r\n");
      out.write("          <div class=\"collection-card-title\">Sports Watches</div>\r\n");
      out.write("          <div class=\"collection-card-meta\">Built for performance and durability</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"dest-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        style=\"text-decoration: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"collection-card-image\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Classic\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collection-card-overlay\"></div>\r\n");
      out.write("        <div class=\"collection-card-chip\">Timeless</div>\r\n");
      out.write("        <div class=\"collection-card-body\">\r\n");
      out.write("          <div class=\"collection-card-tag\">Classic Designs</div>\r\n");
      out.write("          <div class=\"collection-card-title\">Classic Watches</div>\r\n");
      out.write("          <div class=\"collection-card-meta\">Sophisticated style for every moment</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"dest-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        style=\"text-decoration: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"collection-card-image\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Smart\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collection-card-overlay\"></div>\r\n");
      out.write("        <div class=\"collection-card-chip\">Tech-Inspired</div>\r\n");
      out.write("        <div class=\"collection-card-body\">\r\n");
      out.write("          <div class=\"collection-card-tag\">Modern Technology</div>\r\n");
      out.write("          <div class=\"collection-card-title\">Smart Watches</div>\r\n");
      out.write("          <div class=\"collection-card-meta\">Connected lifestyle features</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"dest-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\"\r\n");
      out.write("        style=\"text-decoration: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"collection-card-image\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Womens\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collection-card-overlay\"></div>\r\n");
      out.write("        <div class=\"collection-card-chip\">Elegant</div>\r\n");
      out.write("        <div class=\"collection-card-body\">\r\n");
      out.write("          <div class=\"collection-card-tag\">For Her</div>\r\n");
      out.write("          <div class=\"collection-card-title\">Women's Collection</div>\r\n");
      out.write("          <div class=\"collection-card-meta\">Elegant designs crafted for women</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- FEATURES -->\r\n");
      out.write("<section class=\"sec\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div\r\n");
      out.write("      style=\"\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: flex-end;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        gap: 1.5rem;\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("      \"\r\n");
      out.write("    >\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"sec-tag\">Why Choose Us</div>\r\n");
      out.write("        <h2 class=\"sec-h\">Everything You Expect<br />from AluGhadi</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p class=\"sec-sub\">\r\n");
      out.write("        We're committed to providing premium quality, exceptional service, and\r\n");
      out.write("        value for money.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"feat-grid\">\r\n");
      out.write("      <a class=\"feat-card\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-green\">&#8986;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">Premium Selection</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          Handpicked watches from renowned international brands. Quality assured\r\n");
      out.write("          with authentic certifications.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">Browse collection &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("      <a class=\"feat-card\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-amber\">&#10004;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">100% Authentic</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          Every watch is verified authentic. We work directly with authorized\r\n");
      out.write("          distributors and manufacturers.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">Learn more &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("      <a class=\"feat-card\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-red\">&#128230;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">Free Shipping</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          Free shipping on orders above Rs 5,000. Safe, insured delivery to your\r\n");
      out.write("          doorstep with tracking.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">View policy &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("      <a class=\"feat-card\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-blue\">&#128260;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">Easy Returns</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          30-day return policy. Change your mind? Full refund, no questions\r\n");
      out.write("          asked. Hassle-free process.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">Details &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("      <a class=\"feat-card\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-green\">&#128142;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">Expert Support</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          Our watch experts are here 24/7. Expert advice on sizing, features,\r\n");
      out.write("          and watch care.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">Contact us &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("      <a\r\n");
      out.write("        class=\"feat-card\"\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("        onclick=\"showModal('warranty'); return false;\"\r\n");
      out.write("        ><div class=\"feat-card-icon icon-bg-red\">&#128737;</div>\r\n");
      out.write("        <div class=\"feat-card-title\">Warranty Coverage</div>\r\n");
      out.write("        <p class=\"feat-card-desc\">\r\n");
      out.write("          All watches backed by manufacturer warranty. Extended warranty options\r\n");
      out.write("          available for peace of mind.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"feat-card-link\">View warranty &rarr;</div></a\r\n");
      out.write("      >\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- SPLIT SECTION -->\r\n");
      out.write("<section class=\"sec\" style=\"background: var(--white)\">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div class=\"split\">\r\n");
      out.write("      <div class=\"split-img\">\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/hero_about.png\"\r\n");
      out.write("          alt=\"Watch Craftsmanship\"\r\n");
      out.write("          style=\"object-position: center\"\r\n");
      out.write("        />\r\n");
      out.write("        <div class=\"split-badge\">\r\n");
      out.write("          <div class=\"sb-ico\">&#8986;</div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"sb-v\">150+</div>\r\n");
      out.write("            <div class=\"sb-l\">Years Experience</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"sec-tag\">Craftsmanship</div>\r\n");
      out.write("        <h2 class=\"sec-h\" style=\"margin-bottom: 1rem\">\r\n");
      out.write("          The Art of<br />Perfect Timekeeping\r\n");
      out.write("        </h2>\r\n");
      out.write("        <p\r\n");
      out.write("          style=\"\r\n");
      out.write("            font-size: 0.88rem;\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("            line-height: 1.78;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          Each watch in our collection represents decades of horological\r\n");
      out.write("          excellence. From Swiss precision to Japanese engineering, we showcase\r\n");
      out.write("          the world's most respected watchmaking traditions.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p\r\n");
      out.write("          style=\"\r\n");
      out.write("            font-size: 0.88rem;\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("            line-height: 1.78;\r\n");
      out.write("            margin-bottom: 1.75rem;\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          Whether you're looking for a statement luxury piece, a reliable\r\n");
      out.write("          everyday companion, or a cutting-edge smartwatch, AluGhadi offers\r\n");
      out.write("          something special for every wrist and every moment.\r\n");
      out.write("        </p>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/about\" class=\"btn-fill\"\r\n");
      out.write("          >Learn Our Story &rarr;</a\r\n");
      out.write("        >\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- NEWSLETTER SECTION -->\r\n");
      out.write("<section\r\n");
      out.write("  class=\"sec\"\r\n");
      out.write("  style=\"\r\n");
      out.write("    background: linear-gradient(135deg, var(--green) 0%, var(--green2) 100%);\r\n");
      out.write("    color: #fff;\r\n");
      out.write("  \"\r\n");
      out.write(">\r\n");
      out.write("  <div class=\"sec-inner\">\r\n");
      out.write("    <div style=\"max-width: 600px; margin: 0 auto; text-align: center\">\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"sec-tag\"\r\n");
      out.write("        style=\"\r\n");
      out.write("          color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("          border-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        \"\r\n");
      out.write("      >\r\n");
      out.write("        Newsletter\r\n");
      out.write("      </div>\r\n");
      out.write("      <h2 class=\"sec-h\" style=\"color: #fff; margin-bottom: 1rem\">\r\n");
      out.write("        Get 10% Off Your First Order\r\n");
      out.write("      </h2>\r\n");
      out.write("      <p\r\n");
      out.write("        style=\"\r\n");
      out.write("          font-size: 0.88rem;\r\n");
      out.write("          color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("          margin-bottom: 1.5rem;\r\n");
      out.write("        \"\r\n");
      out.write("      >\r\n");
      out.write("        Subscribe to our newsletter and receive exclusive offers, new arrivals,\r\n");
      out.write("        and watch care tips directly in your inbox.\r\n");
      out.write("      </p>\r\n");
      out.write("      <form style=\"display: flex; gap: 0.5rem; margin-bottom: 1rem\">\r\n");
      out.write("        <input\r\n");
      out.write("          type=\"email\"\r\n");
      out.write("          placeholder=\"Enter your email\"\r\n");
      out.write("          style=\"\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("          \"\r\n");
      out.write("          required\r\n");
      out.write("        />\r\n");
      out.write("        <button\r\n");
      out.write("          type=\"submit\"\r\n");
      out.write("          class=\"btn-fill\"\r\n");
      out.write("          style=\"background: #fff; color: var(--green)\"\r\n");
      out.write("        >\r\n");
      out.write("          Subscribe\r\n");
      out.write("        </button>\r\n");
      out.write("      </form>\r\n");
      out.write("      <p style=\"font-size: 0.7rem; color: rgba(255, 255, 255, 0.7)\">\r\n");
      out.write("        We respect your privacy. Unsubscribe at any time.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
