/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-18 10:06:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1773971807624L));
    _jspx_dependants.put("jar:file:/C:/Users/ACER/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664432778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Sign In | AluGhadi</title>\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("  <style>\r\n");
      out.write("    :root {\r\n");
      out.write("      --green:#1a6b38; --green2:#258a4a; --green-light:#e4f4eb; --green-mid:#b2d9c0;\r\n");
      out.write("      --accent:#3dba62; --text:#0b1c10; --muted:#4e6a59; --border:#d4e5da;\r\n");
      out.write("      --bg:#f2f6f2; --white:#ffffff;\r\n");
      out.write("      --ff:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;\r\n");
      out.write("      --ease:cubic-bezier(0.16,1,0.3,1);\r\n");
      out.write("    }\r\n");
      out.write("    *,*::before,*::after{margin:0;padding:0;box-sizing:border-box;}\r\n");
      out.write("    body{font-family:var(--ff);background:var(--bg);color:var(--text);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1.5rem;}\r\n");
      out.write("    a{text-decoration:none;color:inherit;}\r\n");
      out.write("\r\n");
      out.write("    .auth-wrap {\r\n");
      out.write("      width:100%;\r\n");
      out.write("      max-width:440px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-logo-row {\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      justify-content:center;\r\n");
      out.write("      margin-bottom:2rem;\r\n");
      out.write("    }\r\n");
      out.write("    .auth-logo-img { height:52px; width:auto; display:block; }\r\n");
      out.write("\r\n");
      out.write("    .auth-card {\r\n");
      out.write("      background:var(--white);\r\n");
      out.write("      border:1.5px solid var(--border);\r\n");
      out.write("      border-radius:20px;\r\n");
      out.write("      padding:2.5rem 2rem;\r\n");
      out.write("      box-shadow:0 4px 32px rgba(10,30,15,.07);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-tabs {\r\n");
      out.write("      display:flex;\r\n");
      out.write("      gap:.4rem;\r\n");
      out.write("      background:var(--bg);\r\n");
      out.write("      border:1.5px solid var(--border);\r\n");
      out.write("      border-radius:12px;\r\n");
      out.write("      padding:.3rem;\r\n");
      out.write("      margin-bottom:2rem;\r\n");
      out.write("    }\r\n");
      out.write("    .auth-tab {\r\n");
      out.write("      flex:1;text-align:center;\r\n");
      out.write("      padding:.55rem 1rem;\r\n");
      out.write("      border-radius:9px;\r\n");
      out.write("      font-size:.84rem;font-weight:600;\r\n");
      out.write("      color:var(--muted);\r\n");
      out.write("      transition:all .2s var(--ease);\r\n");
      out.write("    }\r\n");
      out.write("    .auth-tab.active {\r\n");
      out.write("      background:var(--white);\r\n");
      out.write("      color:var(--text);\r\n");
      out.write("      font-weight:700;\r\n");
      out.write("      box-shadow:0 1px 6px rgba(0,0,0,.08);\r\n");
      out.write("    }\r\n");
      out.write("    .auth-tab:hover:not(.active){color:var(--text);}\r\n");
      out.write("\r\n");
      out.write("    .auth-title {font-size:1.4rem;font-weight:900;letter-spacing:-.025em;margin-bottom:.35rem;}\r\n");
      out.write("    .auth-sub {font-size:.84rem;color:var(--muted);margin-bottom:1.75rem;line-height:1.6;}\r\n");
      out.write("\r\n");
      out.write("    .auth-alert {\r\n");
      out.write("      padding:.75rem 1rem;border-radius:10px;font-size:.82rem;font-weight:600;margin-bottom:1.2rem;display:flex;align-items:center;gap:.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .auth-alert-error {background:#fff1f1;color:#b91c1c;border:1.5px solid rgba(185,28,28,.15);}\r\n");
      out.write("    .auth-alert-success{background:var(--green-light);color:var(--green);border:1.5px solid var(--green-mid);}\r\n");
      out.write("\r\n");
      out.write("    .fg {margin-bottom:1.2rem;}\r\n");
      out.write("    .fg label {display:block;font-size:.75rem;font-weight:700;color:var(--text);margin-bottom:.42rem;letter-spacing:.015em;}\r\n");
      out.write("    .input-wrap {position:relative;}\r\n");
      out.write("    .input-wrap input {\r\n");
      out.write("      width:100%;padding:.75rem 2.6rem .75rem .95rem;\r\n");
      out.write("      background:var(--bg);border:1.5px solid var(--border);border-radius:11px;\r\n");
      out.write("      font-family:var(--ff);font-size:.875rem;color:var(--text);outline:none;\r\n");
      out.write("      transition:all .2s var(--ease);\r\n");
      out.write("    }\r\n");
      out.write("    .input-wrap input:focus {border-color:var(--green);background:var(--white);box-shadow:0 0 0 3px rgba(26,107,56,.08);}\r\n");
      out.write("    .input-wrap input::placeholder{color:#88a492;}\r\n");
      out.write("    .input-icon {\r\n");
      out.write("      position:absolute;right:.8rem;top:50%;transform:translateY(-50%);\r\n");
      out.write("      color:#88a492;display:flex;align-items:center;cursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-row {display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem;}\r\n");
      out.write("    .auth-check {display:flex;align-items:center;gap:.45rem;font-size:.8rem;color:var(--muted);cursor:pointer;}\r\n");
      out.write("    .auth-check input{accent-color:var(--green);}\r\n");
      out.write("    .auth-forgot {font-size:.8rem;color:var(--green);font-weight:600;}\r\n");
      out.write("    .auth-forgot:hover{text-decoration:underline;}\r\n");
      out.write("\r\n");
      out.write("    .auth-btn {\r\n");
      out.write("      width:100%;padding:.85rem;\r\n");
      out.write("      background:linear-gradient(135deg,var(--green) 0%,var(--green2) 100%);\r\n");
      out.write("      color:#fff;border:none;border-radius:12px;\r\n");
      out.write("      font-family:var(--ff);font-size:.9rem;font-weight:700;\r\n");
      out.write("      cursor:pointer;transition:all .22s var(--ease);\r\n");
      out.write("      box-shadow:0 3px 14px rgba(26,107,56,.28);\r\n");
      out.write("    }\r\n");
      out.write("    .auth-btn:hover{transform:translateY(-2px);box-shadow:0 8px 26px rgba(26,107,56,.38);}\r\n");
      out.write("    .auth-btn:active{transform:none;}\r\n");
      out.write("\r\n");
      out.write("    .auth-switch {text-align:center;margin-top:1.5rem;font-size:.82rem;color:var(--muted);}\r\n");
      out.write("    .auth-switch a {color:var(--green);font-weight:700;}\r\n");
      out.write("    .auth-switch a:hover{text-decoration:underline;}\r\n");
      out.write("\r\n");
      out.write("    .auth-back {text-align:center;margin-top:1rem;}\r\n");
      out.write("    .auth-back a {font-size:.78rem;color:var(--muted);display:inline-flex;align-items:center;gap:.3rem;}\r\n");
      out.write("    .auth-back a:hover{color:var(--green);}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"auth-wrap\">\r\n");
      out.write("  <div class=\"auth-logo-row\">\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath());
      out.write("/static/images/alughadiweblogo.png\" alt=\"AluGhadi\" class=\"auth-logo-img\" />\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"auth-card\">\r\n");
      out.write("    <div class=\"auth-tabs\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"    class=\"auth-tab active\">Sign In</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" class=\"auth-tab\">Register</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"auth-title\">Welcome back</h1>\r\n");
      out.write("    <p class=\"auth-sub\">Sign in to your AluGhadi account to continue.</p>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">\r\n");
      out.write("      <div class=\"fg\">\r\n");
      out.write("        <label for=\"username\">Username</label>\r\n");
      out.write("        <div class=\"input-wrap\">\r\n");
      out.write("          <input id=\"username\" name=\"username\" type=\"text\" placeholder=\"Enter your username\"\r\n");
      out.write("                 autocomplete=\"username\" required value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("          <span class=\"input-icon\">\r\n");
      out.write("            <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"><path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"/><circle cx=\"12\" cy=\"7\" r=\"4\"/></svg>\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"fg\">\r\n");
      out.write("        <label for=\"password\">Password</label>\r\n");
      out.write("        <div class=\"input-wrap\">\r\n");
      out.write("          <input id=\"password\" name=\"password\" type=\"password\" placeholder=\"Enter your password\"\r\n");
      out.write("                 autocomplete=\"current-password\" required />\r\n");
      out.write("          <span class=\"input-icon\" id=\"pw-toggle\" onclick=\"togglePw()\" role=\"button\" aria-label=\"Toggle password\">\r\n");
      out.write("            <svg id=\"pw-icon-hide\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"><path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>\r\n");
      out.write("            <svg id=\"pw-icon-show\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" style=\"display:none;\"><path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/></svg>\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-row\">\r\n");
      out.write("        <label class=\"auth-check\">\r\n");
      out.write("          <input type=\"checkbox\" name=\"remember\" /> Remember me\r\n");
      out.write("        </label>\r\n");
      out.write("        <a href=\"#\" class=\"auth-forgot\">Forgot password?</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\" class=\"auth-btn\">Sign In</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-switch\">\r\n");
      out.write("      Don't have an account? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Create one</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"auth-back\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("      <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\"><polyline points=\"15 18 9 12 15 6\"/></svg>\r\n");
      out.write("      Back to AluGhadi\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  function togglePw() {\r\n");
      out.write("    var inp  = document.getElementById('password');\r\n");
      out.write("    var hide = document.getElementById('pw-icon-hide');\r\n");
      out.write("    var show = document.getElementById('pw-icon-show');\r\n");
      out.write("    if (inp.type === 'password') {\r\n");
      out.write("      inp.type = 'text';\r\n");
      out.write("      hide.style.display = 'none';\r\n");
      out.write("      show.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("      inp.type = 'password';\r\n");
      out.write("      hide.style.display = 'block';\r\n");
      out.write("      show.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(139,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginError}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <div class=\"auth-alert auth-alert-error\">\r\n");
          out.write("        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"/></svg>\r\n");
          out.write("        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginError}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("      </div>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/login.jsp(145,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.registered}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <div class=\"auth-alert auth-alert-success\">\r\n");
          out.write("        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg>\r\n");
          out.write("        Account created! Please sign in.\r\n");
          out.write("      </div>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(157,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.username}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/login.jsp(157,57) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setDefault("");
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    }
    return false;
  }
}
