/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-23 11:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class for_002dher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  request.setAttribute("pageTitle", "Gifts For Her | AluGhadi Watches");
  request.setAttribute("pageDesc", "Curated watch gifts for her — elegant, expressive, and made to be treasured. Browse our women's gift collection.");
  request.setAttribute("activeNav", "gifting");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-hero forher-hero\">\r\n");
      out.write("  <div class=\"ph-img\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"For Her — Women's Watch Collection\" />\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"ph-ov\" style=\"background:linear-gradient(170deg,rgba(30,10,30,0.22) 0%,rgba(20,8,25,0.90) 100%);\"></div>\r\n");
      out.write("  <div class=\"ph-ov-side\"></div>\r\n");
      out.write("  <div class=\"ph-body\">\r\n");
      out.write("    <div class=\"ph-chip\">&#9792; Gift Guide</div>\r\n");
      out.write("    <h1 class=\"ph-h\">For Her</h1>\r\n");
      out.write("    <p class=\"ph-sub\">Elegant, expressive, and crafted to be treasured. Timepieces she'll reach for every day.</p>\r\n");
      out.write("    <div style=\"margin-top:1.5rem;display:flex;gap:0.8rem;flex-wrap:wrap;\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-fill\" style=\"background:linear-gradient(135deg,#8b4a9e,#c9689a);\">Shop Women's Watches</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/for-him\" class=\"forhim-switch-btn\">Switch to For Him &#8594;</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pg-body\">\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"forhim-breadcrumb\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a>\r\n");
      out.write("    <span>&#8250;</span>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\">Gift Guide</a>\r\n");
      out.write("    <span>&#8250;</span>\r\n");
      out.write("    <span>For Her</span>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"forhim-filter-row\">\r\n");
      out.write("    <div class=\"forhim-filter-label\">Filter by style:</div>\r\n");
      out.write("    <div class=\"tabs-wrap\" style=\"margin-bottom:0;\">\r\n");
      out.write("      <button class=\"tab active\" onclick=\"filterCards('all', this)\">All Styles</button>\r\n");
      out.write("      <button class=\"tab\" onclick=\"filterCards('elegant', this)\">Elegant</button>\r\n");
      out.write("      <button class=\"tab\" onclick=\"filterCards('minimal', this)\">Minimal</button>\r\n");
      out.write("      <button class=\"tab\" onclick=\"filterCards('bold', this)\">Bold</button>\r\n");
      out.write("      <button class=\"tab\" onclick=\"filterCards('luxury', this)\">Luxury</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"forhim-grid\" id=\"forher-grid\">\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal\" data-category=\"elegant\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Elegant Essential\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-forher-elegant\">Elegant</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Elegant Essential</div>\r\n");
      out.write("        <p>Refined rose gold case with a delicate mesh band. Designed for every occasion, every day.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 6,500 – 12,000</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal reveal-delay-1\" data-category=\"minimal\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Modern Minimal\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-minimal\">Minimal</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Modern Minimal</div>\r\n");
      out.write("        <p>Clean white dial with a slim profile. Understated style that complements any outfit effortlessly.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 5,000 – 10,000</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal reveal-delay-2\" data-category=\"bold\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Statement Bold\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-forher-bold\">Bold</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Statement Bold</div>\r\n");
      out.write("        <p>Oversized dial with diamant&eacute;-cut accents. A bold statement for the woman who owns the room.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 10,000 – 20,000</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal reveal-delay-3\" data-category=\"luxury elegant\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Luxury Jewelled\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-luxury\">Luxury</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Jewelled Luxury</div>\r\n");
      out.write("        <p>Crystal-set bezel with mother-of-pearl dial. The pinnacle of feminine watchmaking.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 35,000+</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal\" data-category=\"elegant minimal\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Everyday Chic\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-forher-elegant\">Elegant</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Everyday Chic</div>\r\n");
      out.write("        <p>Versatile silicone straps in pastel tones. Light, sporty, and effortlessly stylish.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 4,500 – 8,000</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"gift-pick-card reveal reveal-delay-1\" data-category=\"luxury bold\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\" alt=\"Prestige Series\" />\r\n");
      out.write("      <div class=\"gift-pick-body\">\r\n");
      out.write("        <div class=\"gift-pick-style-tag gift-pick-style-luxury\">Luxury</div>\r\n");
      out.write("        <div class=\"gift-pick-title\">Prestige Series</div>\r\n");
      out.write("        <p>Swiss movement, gold-plated case. For milestones, anniversaries, and once-in-a-lifetime moments.</p>\r\n");
      out.write("        <div class=\"forhim-card-footer\">\r\n");
      out.write("          <div class=\"gift-pick-meta\">NPR 50,000+</div>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"forhim-card-btn forher-card-btn\">View &#8594;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"forhim-back-row\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gifting\" class=\"forhim-back-link\">\r\n");
      out.write("      &#8592; Back to Gift Guide\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/for-him\" class=\"forhim-switch-link\">\r\n");
      out.write("      Switch to For Him &#8594;\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".forher-hero { min-height: 60vh; }\r\n");
      out.write(".forhim-switch-btn {\r\n");
      out.write("  display:     inline-flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap:         0.4rem;\r\n");
      out.write("  padding:     0.88rem 1.6rem;\r\n");
      out.write("  background:  rgba(255,255,255,0.14);\r\n");
      out.write("  border:      1px solid rgba(255,255,255,0.28);\r\n");
      out.write("  border-radius: 12px;\r\n");
      out.write("  color:       #fff;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  font-size:   0.9rem;\r\n");
      out.write("  backdrop-filter: blur(8px);\r\n");
      out.write("  transition:  all 0.22s;\r\n");
      out.write("}\r\n");
      out.write(".forhim-switch-btn:hover { background: rgba(255,255,255,0.25); }\r\n");
      out.write("\r\n");
      out.write("/* For Her style-specific tags */\r\n");
      out.write(".gift-pick-style-forher-elegant {\r\n");
      out.write("  background: #fff0f8;\r\n");
      out.write("  color:      #b8468a;\r\n");
      out.write("}\r\n");
      out.write(".gift-pick-style-forher-bold {\r\n");
      out.write("  background: #fff4e0;\r\n");
      out.write("  color:      #c87a20;\r\n");
      out.write("}\r\n");
      out.write(".forher-card-btn { color: #b8468a !important; }\r\n");
      out.write(".forher-card-btn:hover { color: #8b2a6e !important; }\r\n");
      out.write("\r\n");
      out.write("/* Reuse styles from for-him */\r\n");
      out.write(".forhim-breadcrumb {\r\n");
      out.write("  display:     flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap:         0.5rem;\r\n");
      out.write("  font-size:   0.78rem;\r\n");
      out.write("  color:       var(--muted);\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write(".forhim-breadcrumb a { color: var(--green); text-decoration: none; font-weight: 600; }\r\n");
      out.write(".forhim-breadcrumb span { color: var(--dim); }\r\n");
      out.write(".forhim-filter-row {\r\n");
      out.write("  display:     flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap:         1.5rem;\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("  flex-wrap:   wrap;\r\n");
      out.write("}\r\n");
      out.write(".forhim-filter-label { font-size: 0.78rem; font-weight: 700; color: var(--muted); }\r\n");
      out.write(".forhim-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin-bottom: 3rem; }\r\n");
      out.write(".gift-pick-style-tag {\r\n");
      out.write("  display:    inline-flex;\r\n");
      out.write("  padding:    0.25rem 0.75rem;\r\n");
      out.write("  border-radius: 999px;\r\n");
      out.write("  font-size:  0.66rem;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  letter-spacing: 0.08em;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  background: var(--green-light);\r\n");
      out.write("  color:      var(--green);\r\n");
      out.write("  margin-bottom: 0.55rem;\r\n");
      out.write("}\r\n");
      out.write(".gift-pick-style-minimal { background: var(--surface); color: var(--muted); }\r\n");
      out.write(".gift-pick-style-luxury  { background: var(--gold-light); color: var(--gold2); }\r\n");
      out.write(".forhim-card-footer { display: flex; justify-content: space-between; align-items: center; margin-top: 0.75rem; padding-top: 0.75rem; border-top: 1px solid var(--border); }\r\n");
      out.write(".forhim-card-btn { font-size: 0.78rem; font-weight: 700; color: var(--green); text-decoration: none; }\r\n");
      out.write(".forhim-back-row { display: flex; justify-content: space-between; align-items: center; padding-top: 2rem; border-top: 1px solid var(--border); flex-wrap: wrap; gap: 1rem; }\r\n");
      out.write(".forhim-back-link, .forhim-switch-link { font-size: 0.84rem; font-weight: 700; color: var(--green); text-decoration: none; }\r\n");
      out.write(".forhim-grid .gift-pick-card.hidden { display: none; }\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 900px)  { .forhim-grid { grid-template-columns: repeat(2, 1fr); } }\r\n");
      out.write("@media (max-width: 600px)  { .forhim-grid { grid-template-columns: 1fr; } }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function filterCards(cat, btn) {\r\n");
      out.write("  document.querySelectorAll('.tabs-wrap .tab').forEach(function(t){ t.classList.remove('active'); });\r\n");
      out.write("  btn.classList.add('active');\r\n");
      out.write("  document.querySelectorAll('#forher-grid .gift-pick-card').forEach(function(card){\r\n");
      out.write("    if (cat === 'all' || (card.dataset.category && card.dataset.category.indexOf(cat) !== -1)) {\r\n");
      out.write("      card.classList.remove('hidden');\r\n");
      out.write("    } else {\r\n");
      out.write("      card.classList.add('hidden');\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
