/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-20 06:46:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class gifting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  request.setAttribute("pageTitle", "Gift Guide | AluGhadi Watches");
  request.setAttribute("pageDesc", "Find the perfect watch gift for him or her. Curated top picks from AluGhadi.");
  request.setAttribute("activeNav", "gifting");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<section class=\"gift-hero\">\r\n");
      out.write("  <video class=\"gift-hero-video\" autoplay muted loop playsinline preload=\"auto\">\r\n");
      out.write("    <source\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/video/water1.mp4\"\r\n");
      out.write("      type=\"video/mp4\"\r\n");
      out.write("    />\r\n");
      out.write("  </video>\r\n");
      out.write("  <div class=\"gift-hero-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"gift-hero-content\">\r\n");
      out.write("    <div class=\"gift-hero-copy\">\r\n");
      out.write("      <p class=\"gift-hero-quote\">\r\n");
      out.write("        \"A gift should feel as timeless as the moment.\"\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"gift-hero-actions\">\r\n");
      out.write("      <a\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/for-him\"\r\n");
      out.write("        class=\"gift-hbtn gift-hbtn-him\"\r\n");
      out.write("        >For Him</a\r\n");
      out.write("      >\r\n");
      out.write("      <a\r\n");
      out.write("        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/for-her\"\r\n");
      out.write("        class=\"gift-hbtn gift-hbtn-her\"\r\n");
      out.write("        >For Her</a\r\n");
      out.write("      >\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"gift-picks-sec\">\r\n");
      out.write("  <div class=\"gift-picks-inner\">\r\n");
      out.write("    <div class=\"gift-picks-header\">\r\n");
      out.write("      <div class=\"sec-tag\">Curated For You</div>\r\n");
      out.write("      <h2 class=\"gift-picks-title\">Our Top Picks</h2>\r\n");
      out.write("      <p class=\"gift-picks-sub\">\r\n");
      out.write("        Handpicked timepieces that make unforgettable gifts.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"gift-picks-grid\">\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Executive Classic\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge\">For Him</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Classic Collection</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Executive Classic</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 8,000</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Elegant Rose\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge gift-pick-badge-her\">For Her</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Elegant Series</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Rose Gold Elegance</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 6,500</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Sport Pro\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge\">For Him</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Sport Collection</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Active Sport Pro</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 5,500</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Prestige Jewelled\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge gift-pick-badge-her\">For Her</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Prestige Series</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Jewelled Prestige</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 35,000</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Minimal Slim\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge\">For Him</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Minimal Collection</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Slim Minimal</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 7,000</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"gift-pick\">\r\n");
      out.write("        <div class=\"gift-pick-img\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/snow_leopard.png\"\r\n");
      out.write("            alt=\"Everyday Chic\"\r\n");
      out.write("          />\r\n");
      out.write("          <span class=\"gift-pick-badge gift-pick-badge-her\">For Her</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gift-pick-info\">\r\n");
      out.write("          <div class=\"gift-pick-brand\">Chic Series</div>\r\n");
      out.write("          <div class=\"gift-pick-name\">Everyday Chic</div>\r\n");
      out.write("          <div class=\"gift-pick-price\">From NPR 4,500</div>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\r\n");
      out.write("            class=\"gift-pick-link\"\r\n");
      out.write("            >Shop Now &#8594;</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"gift-picks-footer\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-fill\"\r\n");
      out.write("        >Browse All Watches &#8594;</a\r\n");
      out.write("      >\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  /* =====================================================\r\n");
      out.write("       GIFT HERO\r\n");
      out.write("       ===================================================== */\r\n");
      out.write("  .gift-hero {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    min-height: 88vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: flex-end;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    margin-top: 80px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    padding: 3rem 4.5vw 4.5rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-video {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    inset: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-overlay {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    inset: 0;\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("      90deg,\r\n");
      out.write("      rgba(6, 18, 10, 0.86) 0%,\r\n");
      out.write("      rgba(6, 18, 10, 0.56) 34%,\r\n");
      out.write("      rgba(6, 18, 10, 0.18) 68%,\r\n");
      out.write("      rgba(6, 18, 10, 0.32) 100%\r\n");
      out.write("    );\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-content {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 1240px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: flex-end;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    gap: 2rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-copy {\r\n");
      out.write("    max-width: 320px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-quote {\r\n");
      out.write("    color: rgba(255, 255, 255, 0.88);\r\n");
      out.write("    font-size: clamp(0.95rem, 1.35vw, 1.1rem);\r\n");
      out.write("    line-height: 1.8;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    letter-spacing: 0.01em;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding-left: 1rem;\r\n");
      out.write("    border-left: 2px solid rgba(201, 164, 82, 0.75);\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    text-shadow: 0 2px 12px rgba(0, 0, 0, 0.36);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hero-actions {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 0.9rem;\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hbtn {\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    padding: 0.95rem 1.7rem;\r\n");
      out.write("    border-radius: 14px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 0.92rem;\r\n");
      out.write("    font-weight: 800;\r\n");
      out.write("    letter-spacing: 0.04em;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    border: 1px solid rgba(255, 255, 255, 0.16);\r\n");
      out.write("    backdrop-filter: blur(14px);\r\n");
      out.write("    transition: all 0.26s var(--ease, cubic-bezier(0.16, 1, 0.3, 1));\r\n");
      out.write("    box-shadow: 0 10px 28px rgba(0, 0, 0, 0.18);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-hbtn:hover {\r\n");
      out.write("    transform: translateY(-3px);\r\n");
      out.write("    box-shadow: 0 14px 36px rgba(0, 0, 0, 0.34);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hbtn-him {\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("      135deg,\r\n");
      out.write("      rgba(26, 107, 56, 0.92) 0%,\r\n");
      out.write("      rgba(9, 27, 14, 0.96) 100%\r\n");
      out.write("    );\r\n");
      out.write("    border-color: rgba(61, 186, 98, 0.35);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-hbtn-him:hover {\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("      135deg,\r\n");
      out.write("      rgba(37, 138, 74, 0.98) 0%,\r\n");
      out.write("      rgba(26, 107, 56, 0.98) 100%\r\n");
      out.write("    );\r\n");
      out.write("    border-color: rgba(61, 186, 98, 0.58);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-hbtn-her {\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("      135deg,\r\n");
      out.write("      rgba(107, 48, 137, 0.92) 0%,\r\n");
      out.write("      rgba(28, 8, 38, 0.96) 100%\r\n");
      out.write("    );\r\n");
      out.write("    border-color: rgba(201, 164, 82, 0.32);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-hbtn-her:hover {\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("      135deg,\r\n");
      out.write("      rgba(155, 80, 185, 0.98) 0%,\r\n");
      out.write("      rgba(90, 25, 110, 0.98) 100%\r\n");
      out.write("    );\r\n");
      out.write("    border-color: rgba(201, 164, 82, 0.58);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* =====================================================\r\n");
      out.write("       TOP PICKS SECTION\r\n");
      out.write("       ===================================================== */\r\n");
      out.write("  .gift-picks-sec {\r\n");
      out.write("    padding: 5rem 2rem 6rem;\r\n");
      out.write("    background: var(--bg, #f2f6f2);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-picks-inner {\r\n");
      out.write("    max-width: 1280px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-picks-header {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 3rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-picks-title {\r\n");
      out.write("    font-size: clamp(1.8rem, 3.5vw, 2.8rem);\r\n");
      out.write("    font-weight: 900;\r\n");
      out.write("    letter-spacing: -0.025em;\r\n");
      out.write("    margin-bottom: 0.5rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-picks-sub {\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("    color: var(--muted, #4e6a59);\r\n");
      out.write("    line-height: 1.65;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-picks-grid {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(3, 1fr);\r\n");
      out.write("    gap: 1.5rem;\r\n");
      out.write("    margin-bottom: 3rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-pick {\r\n");
      out.write("    background: var(--white, #fff);\r\n");
      out.write("    border: 1.5px solid var(--border, #d4e5da);\r\n");
      out.write("    border-radius: 18px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    transition: all 0.28s cubic-bezier(0.16, 1, 0.3, 1);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick:hover {\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("    box-shadow: 0 14px 40px rgba(10, 30, 15, 0.12);\r\n");
      out.write("    border-color: var(--green-mid, #b2d9c0);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-pick-img {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 220px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background: var(--surface, #eaf0ea);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-img img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    transition: transform 0.45s cubic-bezier(0.16, 1, 0.3, 1);\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick:hover .gift-pick-img img {\r\n");
      out.write("    transform: scale(1.06);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-pick-badge {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0.85rem;\r\n");
      out.write("    left: 0.85rem;\r\n");
      out.write("    font-size: 0.66rem;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    letter-spacing: 0.08em;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    background: var(--green, #1a6b38);\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 0.28rem 0.7rem;\r\n");
      out.write("    border-radius: 999px;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-badge-her {\r\n");
      out.write("    background: #9b4ab2;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-pick-info {\r\n");
      out.write("    padding: 1.2rem 1.3rem 1.4rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-brand {\r\n");
      out.write("    font-size: 0.65rem;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    letter-spacing: 0.12em;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: var(--green, #1a6b38);\r\n");
      out.write("    margin-bottom: 0.35rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-name {\r\n");
      out.write("    font-size: 1.05rem;\r\n");
      out.write("    font-weight: 800;\r\n");
      out.write("    letter-spacing: -0.015em;\r\n");
      out.write("    margin-bottom: 0.3rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-price {\r\n");
      out.write("    font-size: 0.82rem;\r\n");
      out.write("    color: var(--muted, #4e6a59);\r\n");
      out.write("    margin-bottom: 0.9rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-link {\r\n");
      out.write("    font-size: 0.8rem;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    color: var(--green, #1a6b38);\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    transition: color 0.18s;\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 0.3rem;\r\n");
      out.write("  }\r\n");
      out.write("  .gift-pick-link:hover {\r\n");
      out.write("    color: var(--green2, #258a4a);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .gift-picks-footer {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 1rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @media (max-width: 1024px) {\r\n");
      out.write("    .gift-hero {\r\n");
      out.write("      padding: 3rem 2.5rem 4rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-content {\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: flex-start;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-actions {\r\n");
      out.write("      margin-left: 0;\r\n");
      out.write("      justify-content: flex-start;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-copy {\r\n");
      out.write("      max-width: 420px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-picks-grid {\r\n");
      out.write("      grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @media (max-width: 640px) {\r\n");
      out.write("    .gift-hero {\r\n");
      out.write("      min-height: 76vh;\r\n");
      out.write("      padding: 2.5rem 1.25rem 3rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-actions {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hbtn {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      min-width: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-copy {\r\n");
      out.write("      max-width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-hero-quote {\r\n");
      out.write("      font-size: 0.95rem;\r\n");
      out.write("      padding-left: 0.85rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gift-picks-grid {\r\n");
      out.write("      grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
