/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-18 18:49:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1773971807624L));
    _jspx_dependants.put("jar:file:/C:/Users/ACER/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664432778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Create Account — AluGhadi Watches</title>\r\n");
      out.write("  <meta name=\"description\" content=\"Join AluGhadi Watches and discover Nepal's finest premium watch collections.\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:ital,wght@0,700;0,900;1,700&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/pages/auth.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"auth-page\">\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== LEFT: BRAND PANEL ===== -->\r\n");
      out.write("  <div class=\"auth-left\">\r\n");
      out.write("    <div class=\"auth-left-bg\"></div>\r\n");
      out.write("    <div class=\"auth-left-pattern\"></div>\r\n");
      out.write("    <div class=\"auth-ring auth-ring-1\"></div>\r\n");
      out.write("    <div class=\"auth-ring auth-ring-2\"></div>\r\n");
      out.write("    <div class=\"auth-ring auth-ring-3\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-left-content\">\r\n");
      out.write("\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"auth-logo\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/alughadiweblogo.png\" alt=\"AluGhadi\" class=\"auth-logo-img\" />\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-brand-center\">\r\n");
      out.write("        <div class=\"auth-brand-eyebrow\">&#9651; Nepal's Premier Watch Destination</div>\r\n");
      out.write("        <div class=\"auth-watch-ring\">\r\n");
      out.write("          <div class=\"auth-watch-face\">AG</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h2 class=\"auth-brand-title\">Join the<br/><span>Collector's Circle</span></h2>\r\n");
      out.write("        <p class=\"auth-brand-sub\">\r\n");
      out.write("          Create your account and unlock exclusive access to Nepal's finest\r\n");
      out.write("          watch collections, early sales, and member-only deals.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"auth-stats\">\r\n");
      out.write("          <div class=\"auth-stat\">\r\n");
      out.write("            <div class=\"auth-stat-n\">500+</div>\r\n");
      out.write("            <div class=\"auth-stat-l\">Watch Styles</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"auth-stat\">\r\n");
      out.write("            <div class=\"auth-stat-n\">12K+</div>\r\n");
      out.write("            <div class=\"auth-stat-l\">Happy Clients</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"auth-stat\">\r\n");
      out.write("            <div class=\"auth-stat-n\">50+</div>\r\n");
      out.write("            <div class=\"auth-stat-l\">Top Brands</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-testimonial\">\r\n");
      out.write("        <p class=\"auth-quote\">\r\n");
      out.write("          Joining AluGhadi was the best decision. Exclusive member prices, early access\r\n");
      out.write("          to new arrivals, and amazing service from day one.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"auth-quote-author\">\r\n");
      out.write("          <div class=\"auth-avatar\">SP</div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"auth-author-name\">Sita Pradhan</div>\r\n");
      out.write("            <div class=\"auth-author-role\">Premium Member &bull; Pokhara</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== RIGHT: FORM PANEL ===== -->\r\n");
      out.write("  <div class=\"auth-right\">\r\n");
      out.write("    <div class=\"auth-form-box\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Tab Switcher -->\r\n");
      out.write("      <div class=\"auth-tabs\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"     class=\"auth-tab\">Sign In</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\"  class=\"auth-tab active\">Register</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <h1 class=\"auth-form-title\">Create account</h1>\r\n");
      out.write("      <p class=\"auth-form-sub\">\r\n");
      out.write("        Join AluGhadi Watches and step into a world of precision, elegance, and timeless style.\r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Register Form -->\r\n");
      out.write("      <form id=\"register-form\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" novalidate>\r\n");
      out.write("\r\n");
      out.write("        <!-- Error Message -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-fg\">\r\n");
      out.write("          <label for=\"reg-username\">Username</label>\r\n");
      out.write("          <div class=\"auth-input-wrap\">\r\n");
      out.write("            <input\r\n");
      out.write("              id=\"reg-username\"\r\n");
      out.write("              name=\"username\"\r\n");
      out.write("              type=\"text\"\r\n");
      out.write("              placeholder=\"Choose a username\"\r\n");
      out.write("              autocomplete=\"username\"\r\n");
      out.write("              required\r\n");
      out.write("              value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("            />\r\n");
      out.write("            <span class=\"auth-input-icon\" title=\"Username\">&#128100;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-fg\">\r\n");
      out.write("          <label for=\"reg-email\">Email Address</label>\r\n");
      out.write("          <div class=\"auth-input-wrap\">\r\n");
      out.write("            <input\r\n");
      out.write("              id=\"reg-email\"\r\n");
      out.write("              name=\"email\"\r\n");
      out.write("              type=\"email\"\r\n");
      out.write("              placeholder=\"you@example.com\"\r\n");
      out.write("              autocomplete=\"email\"\r\n");
      out.write("              required\r\n");
      out.write("              value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("            />\r\n");
      out.write("            <span class=\"auth-input-icon\" title=\"Email\">&#9993;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-fg\">\r\n");
      out.write("          <label for=\"reg-password\">Password</label>\r\n");
      out.write("          <div class=\"auth-input-wrap\">\r\n");
      out.write("            <input\r\n");
      out.write("              id=\"reg-password\"\r\n");
      out.write("              name=\"password\"\r\n");
      out.write("              type=\"password\"\r\n");
      out.write("              placeholder=\"Create a strong password\"\r\n");
      out.write("              autocomplete=\"new-password\"\r\n");
      out.write("              required\r\n");
      out.write("              oninput=\"checkStrength(this.value)\"\r\n");
      out.write("            />\r\n");
      out.write("            <span\r\n");
      out.write("              class=\"auth-input-icon\"\r\n");
      out.write("              id=\"pw-reg-toggle\"\r\n");
      out.write("              onclick=\"togglePw('reg-password','pw-reg-toggle')\"\r\n");
      out.write("              title=\"Show / hide password\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("            >&#128065;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Strength bar -->\r\n");
      out.write("          <div class=\"pass-strength\">\r\n");
      out.write("            <div class=\"pass-strength-bar\" id=\"strength-bar\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-fg\">\r\n");
      out.write("          <label for=\"reg-cpassword\">Confirm Password</label>\r\n");
      out.write("          <div class=\"auth-input-wrap\">\r\n");
      out.write("            <input\r\n");
      out.write("              id=\"reg-cpassword\"\r\n");
      out.write("              name=\"cpassword\"\r\n");
      out.write("              type=\"password\"\r\n");
      out.write("              placeholder=\"Repeat your password\"\r\n");
      out.write("              autocomplete=\"new-password\"\r\n");
      out.write("              required\r\n");
      out.write("            />\r\n");
      out.write("            <span\r\n");
      out.write("              class=\"auth-input-icon\"\r\n");
      out.write("              id=\"pw-cpw-toggle\"\r\n");
      out.write("              onclick=\"togglePw('reg-cpassword','pw-cpw-toggle')\"\r\n");
      out.write("              title=\"Show / hide password\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("            >&#128065;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"auth-btn\" id=\"register-submit-btn\">\r\n");
      out.write("          Create Account &#8594;\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"auth-terms\">\r\n");
      out.write("          By creating an account, you agree to our\r\n");
      out.write("          <a href=\"#\">Terms of Service</a> and <a href=\"#\">Privacy Policy</a>.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-switch\">\r\n");
      out.write("        Already have an account?\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Sign in</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-back-home\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">&#8592; Back to AluGhadi Home</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /auth-page -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  function togglePw(inputId, iconId) {\r\n");
      out.write("    var inp  = document.getElementById(inputId);\r\n");
      out.write("    var icon = document.getElementById(iconId);\r\n");
      out.write("    if (!inp || !icon) return;\r\n");
      out.write("    if (inp.type === 'password') {\r\n");
      out.write("      inp.type = 'text';\r\n");
      out.write("      icon.textContent = '\\uD83D\\uDE48';\r\n");
      out.write("    } else {\r\n");
      out.write("      inp.type = 'password';\r\n");
      out.write("      icon.innerHTML = '&#128065;';\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function checkStrength(val) {\r\n");
      out.write("    var bar = document.getElementById('strength-bar');\r\n");
      out.write("    if (!bar) return;\r\n");
      out.write("    bar.className = 'pass-strength-bar';\r\n");
      out.write("    if (!val) { bar.style.width = '0'; return; }\r\n");
      out.write("    var score = 0;\r\n");
      out.write("    if (val.length >= 8)              score++;\r\n");
      out.write("    if (/[A-Z]/.test(val))            score++;\r\n");
      out.write("    if (/[0-9]/.test(val))            score++;\r\n");
      out.write("    if (/[^A-Za-z0-9]/.test(val))    score++;\r\n");
      out.write("    if (val.length < 6) {\r\n");
      out.write("      bar.classList.add('s-weak');\r\n");
      out.write("    } else if (score <= 1) {\r\n");
      out.write("      bar.classList.add('s-weak');\r\n");
      out.write("    } else if (score === 2) {\r\n");
      out.write("      bar.classList.add('s-fair');\r\n");
      out.write("    } else if (score === 3) {\r\n");
      out.write("      bar.classList.add('s-good');\r\n");
      out.write("    } else {\r\n");
      out.write("      bar.classList.add('s-strong');\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/register.jsp(97,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <p class=\"error\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</p>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/register.jsp(98,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/register.jsp(111,21) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.username}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/register.jsp(111,21) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setDefault("");
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/register.jsp(127,21) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/register.jsp(127,21) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setDefault("");
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    }
    return false;
  }
}
